name 'IBMCookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs and configures various applications and services'
long_description 'Installs and Configures Tomcat, IIS, WLP, DB2 and WAS Network Deployment'
version '0.1.0'

depends 'tomcat'
depends 'iis'
depends 'wlp'
